version: '3.7'

services:
  # Flask Frontend Service
  webapp:
    build: . # Builds from the root directory using DhristiAI/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AI_SERVER_URL=${AI_SERVER_URL}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - nginx-rtmp
      - ai-backend

  # NGINX Media Server Service
  nginx-rtmp:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935" # RTMP port
      - "8080:80"   # HLS playback port
    volumes:
      - ./AI_RTMP_Server/nginx.conf:/etc/nginx/nginx.conf:ro

  # FastAPI AI Backend Service
  ai-backend:
    build: ./AI_RTMP_Server # Builds from the AI_RTMP_Server directory
    ports:
      - "8000:8000"